import { pickLocalizedCopy } from '../../shared/modelLocale'

const onePlusCopy = {
  ru: {
    general: {
      headerSettings: 'Настройки',
      searchPlaceholder: 'Поиск',
      profileSubtitle: 'Управляйте сведениями об аккаунте и его безопасностью.',
      airplaneModeTitle: 'Авиарежим',
      wifiTitle: 'Wi-Fi',
      bluetoothTitle: 'Bluetooth',
      bluetoothConnected: 'Подключено',
      mobileNetworkTitle: 'Мобильная сеть',
      deviceConnectionsTitle: 'Подключение к устройствам',
      homeLockStyleTitle: 'Главный экран, экран блокировки и стиль',
      screenBrightnessTitle: 'Экран и яркость',
      soundVibrationTitle: 'Звуки и вибрация',
      notificationsQuickTitle: 'Уведомления и быстрые настройки',
      securityPrivacyTitle: 'Защита и конфиденциальность',
      safetyEmergencyTitle: 'Безопасность и экстренные случаи',
      locationTitle: 'Местоположение',
      wellbeingTitle: 'Цифровое благополучие и родительский контроль',
      appsTitle: 'Приложения',
      batteryTitle: 'Батарея',
      plusKeyTitle: 'Plus Key',
      accessibilityTitle: 'Специальные возможности и удобство',
      oneplusAiTitle: 'OnePlus AI',
      systemUpdateTitle: 'Система и обновление',
      aboutDeviceTitle: 'Об устройстве',
      usersAccountsTitle: 'Пользователи и аккаунты',
      googleTitle: 'Google',
      helpFeedbackTitle: 'Справка и отзывы',
    },
    wifi: {
      headerTitle: 'Wi-Fi',
      toggleTitle: 'Wi-Fi',
      secondWordSyncing: 'Синхронизация второго слова с устройством...',
      secondWordFailed: 'Не удалось синхронизировать второе слово',
      helperTitle: 'Помощник по Wi-Fi',
      savedNetworksTitle: 'Сохраненные сети',
      availableNetworksTitle: 'Доступные сети',
      refreshLabel: 'Обновить',
      addNetworkTitle: 'Добавить сеть',
    },
  },
  de: {
    general: {
      headerSettings: 'Einstellungen',
      searchPlaceholder: 'Suchen',
      profileSubtitle: 'Kontodaten und Sicherheit verwalten.',
      airplaneModeTitle: 'Flugmodus',
      wifiTitle: 'WLAN',
      bluetoothTitle: 'Bluetooth',
      bluetoothConnected: 'Verbunden',
      mobileNetworkTitle: 'Mobiles Netzwerk',
      deviceConnectionsTitle: 'Geräteverbindungen',
      homeLockStyleTitle: 'Startbildschirm, Sperrbildschirm und Stil',
      screenBrightnessTitle: 'Display und Helligkeit',
      soundVibrationTitle: 'Töne und Vibration',
      notificationsQuickTitle: 'Benachrichtigungen und Schnellzugriff',
      securityPrivacyTitle: 'Sicherheit und Datenschutz',
      safetyEmergencyTitle: 'Sicherheit und Notfall',
      locationTitle: 'Standort',
      wellbeingTitle: 'Digitales Wohlbefinden und Kindersicherung',
      appsTitle: 'Apps',
      batteryTitle: 'Akku',
      plusKeyTitle: 'Plus Key',
      accessibilityTitle: 'Bedienungshilfen und Komfort',
      oneplusAiTitle: 'OnePlus AI',
      systemUpdateTitle: 'System und Updates',
      aboutDeviceTitle: 'Über das Gerät',
      usersAccountsTitle: 'Benutzer und Konten',
      googleTitle: 'Google',
      helpFeedbackTitle: 'Hilfe und Feedback',
    },
    wifi: {
      headerTitle: 'WLAN',
      toggleTitle: 'WLAN',
      secondWordSyncing: 'Zweites Wort wird mit dem Gerat synchronisiert...',
      secondWordFailed: 'Zweites Wort konnte nicht synchronisiert werden',
      helperTitle: 'WLAN-Assistent',
      savedNetworksTitle: 'Gespeicherte Netzwerke',
      availableNetworksTitle: 'Verfügbare Netzwerke',
      refreshLabel: 'Aktualisieren',
      addNetworkTitle: 'Netzwerk hinzufügen',
    },
  },
  en: {
    general: {
      headerSettings: 'Settings',
      searchPlaceholder: 'Search',
      profileSubtitle: 'Manage your account details and security.',
      airplaneModeTitle: 'Airplane mode',
      wifiTitle: 'Wi-Fi',
      bluetoothTitle: 'Bluetooth',
      bluetoothConnected: 'Connected',
      mobileNetworkTitle: 'Mobile network',
      deviceConnectionsTitle: 'Device connection',
      homeLockStyleTitle: 'Home screen, lock screen and style',
      screenBrightnessTitle: 'Display and brightness',
      soundVibrationTitle: 'Sounds and vibration',
      notificationsQuickTitle: 'Notifications and quick settings',
      securityPrivacyTitle: 'Security and privacy',
      safetyEmergencyTitle: 'Safety and emergency',
      locationTitle: 'Location',
      wellbeingTitle: 'Digital wellbeing and parental controls',
      appsTitle: 'Apps',
      batteryTitle: 'Battery',
      plusKeyTitle: 'Plus Key',
      accessibilityTitle: 'Accessibility and convenience',
      oneplusAiTitle: 'OnePlus AI',
      systemUpdateTitle: 'System and updates',
      aboutDeviceTitle: 'About device',
      usersAccountsTitle: 'Users and accounts',
      googleTitle: 'Google',
      helpFeedbackTitle: 'Help and feedback',
    },
    wifi: {
      headerTitle: 'Wi-Fi',
      toggleTitle: 'Wi-Fi',
      secondWordSyncing: 'Syncing second word with device...',
      secondWordFailed: 'Failed to sync second word',
      helperTitle: 'Wi-Fi assistant',
      savedNetworksTitle: 'Saved networks',
      availableNetworksTitle: 'Available networks',
      refreshLabel: 'Refresh',
      addNetworkTitle: 'Add network',
    },
  },
}

export function getOnePlusCopy(locale) {
  return pickLocalizedCopy(onePlusCopy, locale, 'en')
}
