import { pickLocalizedCopy } from '../../shared/modelLocale'

const huaweiCopy = {
  ru: {
    general: {
      headerSettings: 'Настройки',
      searchPlaceholder: 'Поиск',
      profileSubtitle: 'Аккаунт HUAWEI, Платежи и покупки, Облако и прочее',
      wifiTitle: 'Wi-Fi',
      bluetoothTitle: 'Bluetooth',
      bluetoothEnabled: 'Включено',
      mobileNetworkTitle: 'Мобильная сеть',
      superDeviceTitle: 'Суперустройство',
      otherConnectionsTitle: 'Другие соединения',
      homeScreenTitle: 'Рабочий экран',
      displayTitle: 'Экран и яркость',
      soundTitle: 'Звуки и вибрация',
      notificationsTitle: 'Уведомления и строка состояния',
      biometricsTitle: 'Биометрические данные и пароли',
      appsServicesTitle: 'Приложения и службы',
      batteryTitle: 'Батарея',
      memoryTitle: 'Память',
      safetyTitle: 'Безопасность',
      privacyTitle: 'Конфиденциальность',
      locationTitle: 'Данные о местоположении',
      wellbeingTitle: 'Цифровой баланс',
      assistantTitle: 'HUAWEI Assistant',
      accessibilityTitle: 'Специальные возможности',
      usersAccountsTitle: 'Пользователи и аккаунты',
      hmsTitle: 'HMS Core',
      systemTitle: 'Система и обновления',
      aboutPhoneTitle: 'О телефоне',
    },
    wifi: {
      headerTitle: 'Wi-Fi',
      toggleTitle: 'Wi-Fi',
      otherSettingsTitle: 'Другие настройки',
      availableTitle: 'ДОСТУПНО',
      protectedLabel: 'Защищено',
    },
  },
  de: {
    general: {
      headerSettings: 'Einstellungen',
      searchPlaceholder: 'Suchen',
      profileSubtitle: 'HUAWEI-Konto, Zahlungen, Cloud und mehr',
      wifiTitle: 'WLAN',
      bluetoothTitle: 'Bluetooth',
      bluetoothEnabled: 'Ein',
      mobileNetworkTitle: 'Mobiles Netzwerk',
      superDeviceTitle: 'Super Device',
      otherConnectionsTitle: 'Weitere Verbindungen',
      homeScreenTitle: 'Startbildschirm',
      displayTitle: 'Anzeige und Helligkeit',
      soundTitle: 'Töne und Vibration',
      notificationsTitle: 'Benachrichtigungen und Statusleiste',
      biometricsTitle: 'Biometrie und Passwörter',
      appsServicesTitle: 'Apps und Dienste',
      batteryTitle: 'Akku',
      memoryTitle: 'Speicher',
      safetyTitle: 'Sicherheit',
      privacyTitle: 'Datenschutz',
      locationTitle: 'Standortdaten',
      wellbeingTitle: 'Digital Balance',
      assistantTitle: 'HUAWEI Assistant',
      accessibilityTitle: 'Bedienungshilfen',
      usersAccountsTitle: 'Benutzer und Konten',
      hmsTitle: 'HMS Core',
      systemTitle: 'System und Updates',
      aboutPhoneTitle: 'Über das Telefon',
    },
    wifi: {
      headerTitle: 'WLAN',
      toggleTitle: 'WLAN',
      otherSettingsTitle: 'Weitere Einstellungen',
      availableTitle: 'VERFÜGBAR',
      protectedLabel: 'Gesichert',
    },
  },
  en: {
    general: {
      headerSettings: 'Settings',
      searchPlaceholder: 'Search',
      profileSubtitle: 'HUAWEI account, Payments, Cloud and more',
      wifiTitle: 'Wi-Fi',
      bluetoothTitle: 'Bluetooth',
      bluetoothEnabled: 'On',
      mobileNetworkTitle: 'Mobile network',
      superDeviceTitle: 'Super Device',
      otherConnectionsTitle: 'Other connections',
      homeScreenTitle: 'Home screen',
      displayTitle: 'Display and brightness',
      soundTitle: 'Sounds and vibration',
      notificationsTitle: 'Notifications and status bar',
      biometricsTitle: 'Biometrics and passwords',
      appsServicesTitle: 'Apps and services',
      batteryTitle: 'Battery',
      memoryTitle: 'Storage',
      safetyTitle: 'Safety',
      privacyTitle: 'Privacy',
      locationTitle: 'Location data',
      wellbeingTitle: 'Digital balance',
      assistantTitle: 'HUAWEI Assistant',
      accessibilityTitle: 'Accessibility',
      usersAccountsTitle: 'Users and accounts',
      hmsTitle: 'HMS Core',
      systemTitle: 'System and updates',
      aboutPhoneTitle: 'About phone',
    },
    wifi: {
      headerTitle: 'Wi-Fi',
      toggleTitle: 'Wi-Fi',
      otherSettingsTitle: 'Other settings',
      availableTitle: 'AVAILABLE',
      protectedLabel: 'Secured',
    },
  },
}

export function getHuaweiCopy(locale) {
  return pickLocalizedCopy(huaweiCopy, locale, 'en')
}
