import { pickLocalizedCopy } from '../show/shared/modelLocale'

const settingsCopy = {
  ru: {
    title: 'Настройки Hacker',
    languageLabel: 'Язык интерфейса',
    modeLabel: 'Режим',
    modeWord: 'Слово',
    modeCard: 'Карта',
    modeWordSet: 'Набор слов',
    wifiNameLabel: 'Название точки',
    cardLabel: 'Карта (из Show экрана)',
    wordSetLabel: 'Наборы слов',
    wordSetSelectLabel: 'Выберите список',
    wordSetCreate: 'Создать список',
    wordSetCreateName: 'Название списка',
    wordSetCreateWords: 'Слова (до 16)',
    wordSetSave: 'Сохранить список',
    wordSetEmptyHint: 'Выберите список или создайте новый.',
    wordSetWordPlaceholder: 'Слово {n}',
    wordSetDefaultPrefix: 'По умолчанию',
    wordSetDeleteConfirmTitle: 'Удалить список?',
    wordSetDeleteConfirmMessage: 'Вы уверены, что хотите удалить список "{name}"?',
    wordSetDeleteCancel: 'Отмена',
    wordSetDeleteOk: 'Удалить',
    delayLabel: 'Задержка до старта (сек)',
    autostopLabel: 'Автостоп (мин)',
    dotToggle:
      'Добавить точку в начало названия точек Wi-fi для того чтобы они были всегда наверху',
    secondWordToggle: 'Добавить второе слово',
    secondWordLabel: 'Второе слово',
    secondWordWhenLabel: 'Когда менять слово',
    secondWordWhenTap: 'По нажатию на Wi-Fi',
    secondWordWhenAfter: 'После трансляции',
    secondWordDelayLabel: 'Задержка перед вторым словом (сек)',
    startOnWifiToggle: 'Автозапуск при входе в Wi-Fi экран',
    learnToggle: 'Режим обучения',
    showUiLabel: 'Show UI',
    themeLabel: 'Тема',
    themeModel: 'Системная',
    themeDark: 'Тёмная',
    themeLight: 'Светлая',
    syncLabel: 'Синхронизация',
    refreshBusy: 'Обновление...',
    refreshIdle: 'Обновить Show UI',
    accessCodeLabel: 'Код доступа',
    resetAccess: 'Сменить код доступа',
    resetHint: 'Сбросит текущую активацию и вернет на экран ввода кода.',
  },
  de: {
    title: 'Hacker Einstellungen',
    languageLabel: 'Sprache',
    modeLabel: 'Modus',
    modeWord: 'Wort',
    modeCard: 'Karte',
    modeWordSet: 'Wortliste',
    wifiNameLabel: 'SSID-Name',
    cardLabel: 'Karte (aus dem Show-Bildschirm)',
    wordSetLabel: 'Wortlisten',
    wordSetSelectLabel: 'Liste auswahlen',
    wordSetCreate: 'Liste erstellen',
    wordSetCreateName: 'Listenname',
    wordSetCreateWords: 'Worter (bis 16)',
    wordSetSave: 'Liste speichern',
    wordSetEmptyHint: 'Liste auswahlen oder neue erstellen.',
    wordSetWordPlaceholder: 'Wort {n}',
    wordSetDefaultPrefix: 'Standard',
    wordSetDeleteConfirmTitle: 'Liste loschen?',
    wordSetDeleteConfirmMessage: 'Mochten Sie die Liste "{name}" wirklich loschen?',
    wordSetDeleteCancel: 'Abbrechen',
    wordSetDeleteOk: 'Loschen',
    delayLabel: 'Startverzögerung (Sek.)',
    autostopLabel: 'Autostopp (Min.)',
    dotToggle:
      'Punkt am Anfang des WLAN-Namens hinzufügen, damit Netzwerke immer oben stehen',
    secondWordToggle: 'Zweites Wort hinzufügen',
    secondWordLabel: 'Zweites Wort',
    secondWordWhenLabel: 'Zeitpunkt für Wortwechsel',
    secondWordWhenTap: 'Beim Tippen auf Wi-Fi',
    secondWordWhenAfter: 'Nach der Übertragung',
    secondWordDelayLabel: 'Verzögerung vor dem zweiten Wort (Sek.)',
    startOnWifiToggle: 'Auto-Start beim Öffnen des Wi-Fi-Bildschirms',
    learnToggle: 'Lernmodus',
    showUiLabel: 'Show UI',
    themeLabel: 'Design',
    themeModel: 'System',
    themeDark: 'Dunkel',
    themeLight: 'Hell',
    syncLabel: 'Synchronisierung',
    refreshBusy: 'Wird aktualisiert...',
    refreshIdle: 'Show UI aktualisieren',
    accessCodeLabel: 'Zugangscode',
    resetAccess: 'Zugangscode ändern',
    resetHint:
      'Setzt die aktuelle Aktivierung zurück und öffnet den Code-Eingabebildschirm.',
  },
  en: {
    title: 'Hacker Settings',
    languageLabel: 'Interface Language',
    modeLabel: 'Mode',
    modeWord: 'Word',
    modeCard: 'Card',
    modeWordSet: 'Word Set',
    wifiNameLabel: 'SSID Name',
    cardLabel: 'Card (from Show screen)',
    wordSetLabel: 'Word Sets',
    wordSetSelectLabel: 'Select list',
    wordSetCreate: 'Create list',
    wordSetCreateName: 'List name',
    wordSetCreateWords: 'Words (up to 16)',
    wordSetSave: 'Save list',
    wordSetEmptyHint: 'Select a list or create a new one.',
    wordSetWordPlaceholder: 'Word {n}',
    wordSetDefaultPrefix: 'Default',
    wordSetDeleteConfirmTitle: 'Delete list?',
    wordSetDeleteConfirmMessage: 'Are you sure you want to delete list "{name}"?',
    wordSetDeleteCancel: 'Cancel',
    wordSetDeleteOk: 'Delete',
    delayLabel: 'Start Delay (sec)',
    autostopLabel: 'Auto-stop (min)',
    dotToggle:
      'Add a dot at the start of Wi-Fi names so they always stay at the top',
    secondWordToggle: 'Add second word',
    secondWordLabel: 'Second word',
    secondWordWhenLabel: 'When to switch word',
    secondWordWhenTap: 'On Wi-Fi tap',
    secondWordWhenAfter: 'After broadcast starts',
    secondWordDelayLabel: 'Delay before second word (sec)',
    startOnWifiToggle: 'Auto-start on Wi-Fi screen open',
    learnToggle: 'Learn mode',
    showUiLabel: 'Show UI',
    themeLabel: 'Theme',
    themeModel: 'System',
    themeDark: 'Dark',
    themeLight: 'Light',
    syncLabel: 'Sync',
    refreshBusy: 'Updating...',
    refreshIdle: 'Refresh Show UI',
    accessCodeLabel: 'Access Code',
    resetAccess: 'Change access code',
    resetHint:
      'Resets current activation and returns to the access code input screen.',
  },
}

export function getSettingsCopy(locale) {
  return pickLocalizedCopy(settingsCopy, locale, 'en')
}
