import { pickLocalizedCopy } from '../show/shared/modelLocale'

const settingsCopy = {
  ru: {
    title: 'Настройки Hacker',
    languageLabel: 'Язык интерфейса',
    modeLabel: 'Режим',
    modeWord: 'Слово',
    modeCard: 'Карта',
    wifiNameLabel: 'Название точки',
    cardLabel: 'Карта (из Show экрана)',
    delayLabel: 'Задержка до старта (сек)',
    autostopLabel: 'Автостоп (мин)',
    dotToggle: 'Добавлять точку в начале SSID',
    secondWordToggle: 'Добавить второе слово',
    secondWordLabel: 'Второе слово',
    secondWordWhenLabel: 'Когда менять слово',
    secondWordWhenTap: 'По нажатию на Wi-Fi',
    secondWordWhenAfter: 'После трансляции',
    secondWordDelayLabel: 'Задержка перед вторым словом (сек)',
    startOnWifiToggle: 'Автозапуск при входе в Wi-Fi экран',
    learnToggle: 'Режим обучения',
    showUiLabel: 'Show UI',
    themeLabel: 'Тема',
    themeModel: 'Системная',
    themeDark: 'Тёмная',
    themeLight: 'Светлая',
    syncLabel: 'Синхронизация',
    refreshBusy: 'Обновление...',
    refreshIdle: 'Обновить Show UI',
    accessCodeLabel: 'Код доступа',
    resetAccess: 'Сменить код доступа',
    resetHint: 'Сбросит текущую активацию и вернет на экран ввода кода.',
  },
  de: {
    title: 'Hacker Einstellungen',
    languageLabel: 'Sprache',
    modeLabel: 'Modus',
    modeWord: 'Wort',
    modeCard: 'Karte',
    wifiNameLabel: 'SSID-Name',
    cardLabel: 'Karte (aus dem Show-Bildschirm)',
    delayLabel: 'Startverzögerung (Sek.)',
    autostopLabel: 'Autostopp (Min.)',
    dotToggle: 'Punkt am Anfang der SSID hinzufügen',
    secondWordToggle: 'Zweites Wort hinzufügen',
    secondWordLabel: 'Zweites Wort',
    secondWordWhenLabel: 'Zeitpunkt für Wortwechsel',
    secondWordWhenTap: 'Beim Tippen auf Wi-Fi',
    secondWordWhenAfter: 'Nach der Übertragung',
    secondWordDelayLabel: 'Verzögerung vor dem zweiten Wort (Sek.)',
    startOnWifiToggle: 'Auto-Start beim Öffnen des Wi-Fi-Bildschirms',
    learnToggle: 'Lernmodus',
    showUiLabel: 'Show UI',
    themeLabel: 'Design',
    themeModel: 'System',
    themeDark: 'Dunkel',
    themeLight: 'Hell',
    syncLabel: 'Synchronisierung',
    refreshBusy: 'Wird aktualisiert...',
    refreshIdle: 'Show UI aktualisieren',
    accessCodeLabel: 'Zugangscode',
    resetAccess: 'Zugangscode ändern',
    resetHint:
      'Setzt die aktuelle Aktivierung zurück und öffnet den Code-Eingabebildschirm.',
  },
  en: {
    title: 'Hacker Settings',
    languageLabel: 'Interface Language',
    modeLabel: 'Mode',
    modeWord: 'Word',
    modeCard: 'Card',
    wifiNameLabel: 'SSID Name',
    cardLabel: 'Card (from Show screen)',
    delayLabel: 'Start Delay (sec)',
    autostopLabel: 'Auto-stop (min)',
    dotToggle: 'Add dot at the start of SSID',
    secondWordToggle: 'Add second word',
    secondWordLabel: 'Second word',
    secondWordWhenLabel: 'When to switch word',
    secondWordWhenTap: 'On Wi-Fi tap',
    secondWordWhenAfter: 'After broadcast starts',
    secondWordDelayLabel: 'Delay before second word (sec)',
    startOnWifiToggle: 'Auto-start on Wi-Fi screen open',
    learnToggle: 'Learn mode',
    showUiLabel: 'Show UI',
    themeLabel: 'Theme',
    themeModel: 'System',
    themeDark: 'Dark',
    themeLight: 'Light',
    syncLabel: 'Sync',
    refreshBusy: 'Updating...',
    refreshIdle: 'Refresh Show UI',
    accessCodeLabel: 'Access Code',
    resetAccess: 'Change access code',
    resetHint:
      'Resets current activation and returns to the access code input screen.',
  },
}

export function getSettingsCopy(locale) {
  return pickLocalizedCopy(settingsCopy, locale, 'en')
}
