import { pickLocalizedCopy } from '../../shared/modelLocale'

const samsungOneUi8Copy = {
  ru: {
    learnCodeLabel: 'Код',
    learnHintCard:
      'Свайп по сегментам под кнопкой "Подключения" выбирает номинал карты. Масть карты задается тапом по нужному сегменту в кнопке "Подключения". Если номинал не выбран, то по умолчанию считается выбранным A (Туз).',
    learnHintWordSet:
      'Свайп по нужному сегменту выбирает его, после чего нажмите "Подключения" для перехода к следующему экрану. Если не делать свайп, то по умолчанию считается выбранным первое слово.',
    headerSettings: 'Настройки',
    profileSub: 'Samsung account',
    general: {
      connectionsTitle: 'Подключения',
      connectionsSubtitle: 'Wi-Fi • Bluetooth • Диспетчер SIM-карт',
      connectedDevicesTitle: 'Подключенные устройства',
      connectedDevicesSubtitle: 'Быстрая отправка • Samsung DeX • Android Auto',
      galaxyAiTitle: 'Galaxy AI',
      galaxyAiSubtitle:
        'Ассистент по письму • Ассистент по заметкам • Ассистент по фотографиям',
      modesTitle: 'Режимы и сценарии',
      modesSubtitle: 'Режимы • Сценарии',
      soundsTitle: 'Звуки и вибрация',
      soundsSubtitle: 'Рингтон • Громкость • Вибрация',
      notificationsTitle: 'Уведомления',
      notificationsSubtitle: 'Строка состояния • Не беспокоить',
      displayTitle: 'Дисплей',
      displaySubtitle: 'Яркость • Комфорт для глаз • Навигационная панель',
      batteryTitle: 'Батарея',
      batterySubtitle: 'Энергосбережение • Зарядка',
      wallpaperTitle: 'Обои и стиль',
      wallpaperSubtitle: 'Обои • Палитра цветов',
      securityPrivacyTitle: 'Безопасность и конфиденциальность',
      securityPrivacySubtitle: 'Биометрия • Разрешения',
      locationTitle: 'Локация',
      locationSubtitle: 'Доступ к местоположению',
      emergencyTitle: 'Экстренные ситуации',
      emergencySubtitle: 'SOS и медданные',
      accountsBackupTitle: 'Учетные записи и архивация',
      accountsBackupSubtitle: 'Управление аккаунтами • Smart Switch',
      googleTitle: 'Google',
      googleSubtitle: 'Службы Google',
      advancedFeaturesTitle: 'Дополнительные функции',
      advancedFeaturesSubtitle: 'Labs • Боковая кнопка',
      wellbeingTitle: 'Использование устройства и родительский контроль',
      wellbeingSubtitle: 'Время экрана • Таймеры',
      deviceCareTitle: 'Обслуживание устройства',
      deviceCareSubtitle: 'Хранилище • Память • Защита',
      appsTitle: 'Приложения',
      appsSubtitle: 'Приложения по умолчанию',
      generalManagementTitle: 'Общие настройки',
      generalManagementSubtitle: 'Язык и клавиатура • Дата и время',
      accessibilityTitle: 'Специальные возможности',
      accessibilitySubtitle: 'Отображение • Слышимость • Подвижность',
      softwareUpdateTitle: 'Обновление ПО',
      softwareUpdateSubtitle: 'Загрузка и установка',
      tipsTitle: 'Советы и руководство пользователя',
      tipsSubtitle: 'Полезные советы • Новые функции',
      aboutPhoneTitle: 'Сведения о телефоне',
      aboutPhoneSubtitle: 'Состояние • Юридическая информация',
      developerOptionsTitle: 'Параметры разработчика',
      developerOptionsSubtitle: 'Открыть экран настроек приложения',
    },
    connections: {
      headerTitle: 'Подключения',
      wifiTitle: 'Wi-Fi',
      wifiCallingTitle: 'Вызовы по Wi-Fi',
      bluetoothTitle: 'Bluetooth',
      nfcTitle: 'NFC и бесконтактные платежи',
      uwbTitle: 'Сверхширокая полоса (UWB)',
      uwbSubtitle: 'Определение точного местоположения устройства поблизости.',
      airplaneModeTitle: 'Авиарежим',
      simManagerTitle: 'Диспетчер SIM-карт',
      mobileNetworksTitle: 'Мобильные сети',
      dataUsageTitle: 'Использование данных',
      hotspotTitle: 'Мобильная точка доступа и модем',
      otherSettingsTitle: 'Другие настройки',
      suggestTitle: 'Ищете что-то другое?',
      suggestSamsungCloud: 'Samsung Cloud',
      suggestLinkToWindows: 'Связь с Windows',
      suggestAndroidAuto: 'Android Auto',
      suggestQuickShare: 'Быстрая отправка',
    },
    wifi: {
      headerTitle: 'Wi-Fi',
      statusOn: 'Включено',
      statusOff: 'Выключено',
      secondWordSyncing: 'Синхронизация второго слова с устройством...',
      secondWordFailed: 'Не удалось синхронизировать второе слово',
      availableNetworksTitle: 'Доступные сети',
      addNetworkTitle: 'Добавить сеть',
    },
  },
  de: {
    learnCodeLabel: 'Code',
    learnHintCard:
      'Durch Wischen in den Segmenten unter "Verbindungen" wird der Kartenwert gewahlt. Die Kartenfarbe wird durch Tippen auf ein Segment in "Verbindungen" gesetzt.',
    learnHintWordSet:
      'Tippen auf die Segmente in den Zeilen darunter wahlt ein Wort aus der aktiven Liste. "Verbindungen" offnet nur den nachsten Bildschirm.',
    headerSettings: 'Einstellungen',
    profileSub: 'Samsung Account',
    general: {
      connectionsTitle: 'Verbindungen',
      connectionsSubtitle: 'WLAN • Bluetooth • SIM-Manager',
      connectedDevicesTitle: 'Verbundene Geräte',
      connectedDevicesSubtitle: 'Quick Share • Samsung DeX • Android Auto',
      galaxyAiTitle: 'Galaxy AI',
      galaxyAiSubtitle: 'Schreib-Assistent • Notizen-Assistent • Foto-Assistent',
      modesTitle: 'Modi und Routinen',
      modesSubtitle: 'Modi • Routinen',
      soundsTitle: 'Töne und Vibration',
      soundsSubtitle: 'Tonmodus • Klingelton',
      notificationsTitle: 'Benachrichtigungen',
      notificationsSubtitle: 'Statusleiste • Nicht stören',
      displayTitle: 'Anzeige',
      displaySubtitle: 'Helligkeit • Augenkomfort • Navigationsleiste',
      batteryTitle: 'Akku',
      batterySubtitle: 'Energiesparen • Laden',
      wallpaperTitle: 'Hintergrundbild und Stil',
      wallpaperSubtitle: 'Hintergr. • Farbpalette',
      securityPrivacyTitle: 'Sicherheit und Datenschutz',
      securityPrivacySubtitle: 'Automatische Sperre • Berechtigungsnutzung',
      locationTitle: 'Standort',
      locationSubtitle: 'Standortanfragen',
      emergencyTitle: 'Sicherheit und Notfall',
      emergencySubtitle: 'Medizinische Informationen • Notfallwarnungen',
      accountsBackupTitle: 'Konten und Sicherung',
      accountsBackupSubtitle: 'Konten verwalten • Smart Switch',
      googleTitle: 'Google',
      googleSubtitle: 'Google-Dienste',
      advancedFeaturesTitle: 'Erweiterte Funktionen',
      advancedFeaturesSubtitle: 'Labs • S Pen • Funktionstaste',
      wellbeingTitle: 'Digitales Wohlbefinden und Kindersicherung',
      wellbeingSubtitle: 'Bildschirmzeit • App-Timer',
      deviceCareTitle: 'Gerätewartung',
      deviceCareSubtitle: 'Speicherplatz • Arbeitsspeicher • App-Schutz',
      appsTitle: 'Apps',
      appsSubtitle: 'Standard-Apps • App-Einstellungen',
      generalManagementTitle: 'Allgemeine Verwaltung',
      generalManagementSubtitle: 'Sprache und Tastatur • Datum und Uhrzeit',
      accessibilityTitle: 'Eingabehilfe',
      accessibilitySubtitle: 'Sichtbarkeit • Hören • Geschicklichkeit',
      softwareUpdateTitle: 'Software-Update',
      softwareUpdateSubtitle: 'Herunterladen und installieren',
      tipsTitle: 'Tipps und Benutzerhandbuch',
      tipsSubtitle: 'Hilfreiche Tipps • Neue Funktionen',
      aboutPhoneTitle: 'Telefoninfo',
      aboutPhoneSubtitle: 'Status • Rechtliche Informationen • Telefonname',
      developerOptionsTitle: 'Entwickleroptionen',
      developerOptionsSubtitle: 'Einstellungsbildschirm der App öffnen',
    },
    connections: {
      headerTitle: 'Verbindungen',
      wifiTitle: 'WLAN',
      wifiCallingTitle: 'WLAN-Anrufe',
      bluetoothTitle: 'Bluetooth',
      nfcTitle: 'NFC und kontaktloses Bezahlen',
      uwbTitle: 'Ultrabreitband (UWB)',
      uwbSubtitle: 'Präzise Standortbestimmung von Geräten in der Nähe.',
      airplaneModeTitle: 'Flugmodus',
      simManagerTitle: 'SIM-Manager',
      mobileNetworksTitle: 'Mobile Netzwerke',
      dataUsageTitle: 'Datennutzung',
      hotspotTitle: 'Mobile Hotspot und Tethering',
      otherSettingsTitle: 'Weitere Verbindungseinstellungen',
      suggestTitle: 'Suchen Sie etwas anderes?',
      suggestSamsungCloud: 'Samsung Cloud',
      suggestLinkToWindows: 'Link zu Windows',
      suggestAndroidAuto: 'Android Auto',
      suggestQuickShare: 'Quick Share',
    },
    wifi: {
      headerTitle: 'WLAN',
      statusOn: 'Ein',
      statusOff: 'Aus',
      secondWordSyncing: 'Zweites Wort wird mit dem Gerat synchronisiert...',
      secondWordFailed: 'Zweites Wort konnte nicht synchronisiert werden',
      availableNetworksTitle: 'Verfügbare Netzwerke',
      addNetworkTitle: 'Netzwerk hinzufügen',
    },
  },
  en: {
    learnCodeLabel: 'Code',
    learnHintCard:
      'Swiping segments below "Connections" selects the card rank. Card suit is selected by tapping a segment inside "Connections".',
    learnHintWordSet:
      'Tapping row segments below selects a word from the active list. "Connections" only opens the next screen.',
    headerSettings: 'Settings',
    profileSub: 'Samsung Account',
    general: {
      connectionsTitle: 'Connections',
      connectionsSubtitle: 'Wi-Fi • Bluetooth • SIM manager',
      connectedDevicesTitle: 'Connected devices',
      connectedDevicesSubtitle: 'Quick Share • Samsung DeX • Android Auto',
      galaxyAiTitle: 'Galaxy AI',
      galaxyAiSubtitle: 'Writing assist • Notes assist • Photo assist',
      modesTitle: 'Modes and Routines',
      modesSubtitle: 'Modes • Routines',
      soundsTitle: 'Sounds and vibration',
      soundsSubtitle: 'Sound mode • Ringtone',
      notificationsTitle: 'Notifications',
      notificationsSubtitle: 'Status bar • Do not disturb',
      displayTitle: 'Display',
      displaySubtitle: 'Brightness • Eye comfort • Navigation bar',
      batteryTitle: 'Battery',
      batterySubtitle: 'Power saving • Charging',
      wallpaperTitle: 'Wallpaper and style',
      wallpaperSubtitle: 'Wallpaper • Color palette',
      securityPrivacyTitle: 'Security and privacy',
      securityPrivacySubtitle: 'Auto lock • Permission usage',
      locationTitle: 'Location',
      locationSubtitle: 'Location requests',
      emergencyTitle: 'Safety and emergency',
      emergencySubtitle: 'Medical info • Emergency alerts',
      accountsBackupTitle: 'Accounts and backup',
      accountsBackupSubtitle: 'Manage accounts • Smart Switch',
      googleTitle: 'Google',
      googleSubtitle: 'Google services',
      advancedFeaturesTitle: 'Advanced features',
      advancedFeaturesSubtitle: 'Labs • S Pen • Side key',
      wellbeingTitle: 'Digital wellbeing and parental controls',
      wellbeingSubtitle: 'Screen time • App timers',
      deviceCareTitle: 'Device care',
      deviceCareSubtitle: 'Storage • Memory • App protection',
      appsTitle: 'Apps',
      appsSubtitle: 'Default apps • App settings',
      generalManagementTitle: 'General management',
      generalManagementSubtitle: 'Language and keyboard • Date and time',
      accessibilityTitle: 'Accessibility',
      accessibilitySubtitle: 'Visibility • Hearing • Dexterity',
      softwareUpdateTitle: 'Software update',
      softwareUpdateSubtitle: 'Download and install',
      tipsTitle: 'Tips and user manual',
      tipsSubtitle: 'Helpful tips • New features',
      aboutPhoneTitle: 'About phone',
      aboutPhoneSubtitle: 'Status • Legal information • Phone name',
      developerOptionsTitle: 'Developer options',
      developerOptionsSubtitle: 'Open app settings screen',
    },
    connections: {
      headerTitle: 'Connections',
      wifiTitle: 'Wi-Fi',
      wifiCallingTitle: 'Wi-Fi calling',
      bluetoothTitle: 'Bluetooth',
      nfcTitle: 'NFC and contactless payments',
      uwbTitle: 'Ultra-wideband (UWB)',
      uwbSubtitle: 'Precise location of nearby devices.',
      airplaneModeTitle: 'Airplane mode',
      simManagerTitle: 'SIM manager',
      mobileNetworksTitle: 'Mobile networks',
      dataUsageTitle: 'Data usage',
      hotspotTitle: 'Mobile hotspot and tethering',
      otherSettingsTitle: 'Other connection settings',
      suggestTitle: 'Looking for something else?',
      suggestSamsungCloud: 'Samsung Cloud',
      suggestLinkToWindows: 'Link to Windows',
      suggestAndroidAuto: 'Android Auto',
      suggestQuickShare: 'Quick Share',
    },
    wifi: {
      headerTitle: 'Wi-Fi',
      statusOn: 'On',
      statusOff: 'Off',
      secondWordSyncing: 'Syncing second word with device...',
      secondWordFailed: 'Failed to sync second word',
      availableNetworksTitle: 'Available networks',
      addNetworkTitle: 'Add network',
    },
  },
}

export function getSamsungOneUi8Copy(locale) {
  return pickLocalizedCopy(samsungOneUi8Copy, locale, 'en')
}
